### ISSUE TITLE
Add new BootStrap Classes

### ISSUE THREAD

**Issue by bjruiz** [bjruiz/potential-robot-shows-app#1]
in index.html and my stylesheet.

**Comment by bjruiz** [comment]
Bootstraps classes I used:

- large button classes with the dark outline
- margin and padding of 2 in the `main`
- bottom margin of 3 in `div`


```html
<main class="m-2 p-2 seeMe">
    <h2 class="header-font">Need to Watch</h2>
    <div class="mb-3">
      <button id="loadBtn" class="btn btn-outline-dark btn-lg">Load Shows</button>
      <button id="clearBtn" class="btn btn-outline-dark btn-lg">Clear Shows</button>
```

**Comment by bjruiz** [comment]
Added a border around my main in my style sheet.

```CSS
.seeMe {
  border-style: dashed;
  border-width: 2px;
  border-color:black;
}
```

**Comment by bjruiz** [comment]
Added a border around my main in my style sheet.

```CSS
.seeMe {
  border-style: dashed;
  border-width: 2px;
  border-color:black;
}
```
